// BTNG Gold Coin - Mock Market Data & Platform Data
// Gold spot: $4,441.84/oz (fawazahmed0 CDN live — June 6 2026)
// Unit 1: BTNGG = 1/1000 oz = $4.4418
// Unit 2: BTNG-G = 1 gram = $4,441.84 / 31.1035 = $142.81
// Unit 3: BTNG-KG = 1 kg = $4,441.84 × 32.1507 = $142,808

export const BTNG_PRICE = 4.4418;        // BTNGG: 1/1000 troy oz XAU
export const BTNG_PRICE_GRAM = 142.81;   // BTNG-G: 1 gram XAU
export const BTNG_PRICE_KILO = 142_808;  // BTNG-KG: 1 kilo XAU
export const GOLD_PRICE_OZ   = 4_441.84; // XAU/USD spot (fawazahmed0 CDN June 6 2026)
export const BTNG_CHANGE_24H = -0.258;
export const BTNG_MARKET_CAP = 4_462_200_000;
export const BTNG_VOLUME = 312_450_000;

export const COINS = [
  // ── BTNG Unit 1: BTNGG — 1/1000 troy oz XAU ($4,441.84 / 1000 = $4.4418) ──
  {
    id: 'btng',
    symbol: 'BTNGG',
    name: 'Bituncoin Gold (1/1000 oz)',
    price: 4.4418,
    change24h: -0.258,
    marketCap: 4_329_500_000,
    volume: 312_450_000,
    logo: '🥇',
    color: '#D4A017',
    isOwned: true,
    balance: 2500,
  },
  // ── BTNG Unit 2: BTNG-G — 1 gram XAU ($4,441.84 / 31.1035 = $142.81) ──────
  {
    id: 'btng-g',
    symbol: 'BTNG-G',
    name: 'Bituncoin Gold (1 gram)',
    price: 142.81,
    change24h: -0.258,
    marketCap: 1_392_000_000,
    volume: 48_200_000,
    logo: '🪙',
    color: '#C8A951',
    isOwned: false,
    balance: 0,
  },
  // ── BTNG Unit 3: BTNG-KG — 1 kilogram XAU ($4,441.84 × 32.1507 = $142,808) ─
  {
    id: 'btng-kg',
    symbol: 'BTNG-KG',
    name: 'Bituncoin Gold (1 kg)',
    price: 142_808,
    change24h: -0.258,
    marketCap: 139_195_000_000,
    volume: 28_000_000,
    logo: '🏅',
    color: '#B8860B',
    isOwned: false,
    balance: 0,
  },
  {
    id: 'btc',
    symbol: 'BTC',
    name: 'Bitcoin',
    price: 107_200,
    change24h: 2.14,
    marketCap: 2_110_000_000_000,
    volume: 48_320_000_000,
    logo: '₿',
    color: '#F7931A',
    isOwned: true,
    balance: 0.045,
  },
  {
    id: 'eth',
    symbol: 'ETH',
    name: 'Ethereum',
    price: 3_840,
    change24h: -1.23,
    marketCap: 463_000_000_000,
    volume: 21_500_000_000,
    logo: 'Ξ',
    color: '#627EEA',
    isOwned: true,
    balance: 1.2,
  },
  {
    id: 'bnb',
    symbol: 'BNB',
    name: 'BNB Chain',
    price: 685,
    change24h: 3.45,
    marketCap: 99_000_000_000,
    volume: 2_100_000_000,
    logo: '◈',
    color: '#F0B90B',
    isOwned: false,
    balance: 0,
  },
  {
    id: 'sol',
    symbol: 'SOL',
    name: 'Solana',
    price: 184,
    change24h: -0.87,
    marketCap: 87_000_000_000,
    volume: 4_300_000_000,
    logo: '◎',
    color: '#9945FF',
    isOwned: false,
    balance: 0,
  },
  {
    id: 'usdt',
    symbol: 'USDT',
    name: 'Tether',
    price: 1.0,
    change24h: 0.01,
    marketCap: 145_000_000_000,
    volume: 95_000_000_000,
    logo: '₮',
    color: '#26A17B',
    isOwned: true,
    balance: 5000,
  },
  {
    id: 'matic',
    symbol: 'MATIC',
    name: 'Polygon',
    price: 0.89,
    change24h: 5.67,
    marketCap: 8_400_000_000,
    volume: 670_000_000,
    logo: '⬡',
    color: '#8247E5',
    isOwned: false,
    balance: 0,
  },
  {
    id: 'xrp',
    symbol: 'XRP',
    name: 'Ripple',
    price: 2.14,
    change24h: -2.11,
    marketCap: 123_000_000_000,
    volume: 7_800_000_000,
    logo: '✕',
    color: '#00AAE4',
    isOwned: false,
    balance: 0,
  },
  {
    id: 'ada',
    symbol: 'ADA',
    name: 'Cardano',
    price: 0.72,
    change24h: 1.34,
    marketCap: 25_400_000_000,
    volume: 980_000_000,
    logo: '₳',
    color: '#0033AD',
    isOwned: false,
    balance: 0,
  },
  {
    id: 'doge',
    symbol: 'DOGE',
    name: 'Dogecoin',
    price: 0.38,
    change24h: 4.12,
    marketCap: 55_600_000_000,
    volume: 3_200_000_000,
    logo: 'Ð',
    color: '#C2A633',
    isOwned: false,
    balance: 0,
  },
  {
    id: 'avax',
    symbol: 'AVAX',
    name: 'Avalanche',
    price: 42.80,
    change24h: -1.55,
    marketCap: 17_900_000_000,
    volume: 780_000_000,
    logo: '🔺',
    color: '#E84142',
    isOwned: false,
    balance: 0,
  },
  {
    id: 'dot',
    symbol: 'DOT',
    name: 'Polkadot',
    price: 9.14,
    change24h: 2.78,
    marketCap: 13_200_000_000,
    volume: 560_000_000,
    logo: '●',
    color: '#E6007A',
    isOwned: false,
    balance: 0,
  },
];

// Sparkline data aligned to live gold price ~$4,441.84/oz → BTNGG ~$4.4418
export const PRICE_HISTORY_7D = [
  4.62, 4.58, 4.55, 4.51, 4.49, 4.47, 4.45, 4.44, 4.44, 4.45, 4.44, 4.44, 4.4418,
];

export const CHART_POINTS_24H = [
  4.46, 4.45, 4.44, 4.46, 4.45, 4.44, 4.43, 4.44, 4.45, 4.44,
  4.43, 4.44, 4.43, 4.42, 4.43, 4.44, 4.43, 4.44, 4.44, 4.43,
  4.44, 4.43, 4.44, 4.4418,
];

// Order book anchored to live BTNGG price ~$4.4418
export const ORDER_BOOK = {
  asks: [
    { price: 4.3440, amount: 1250, total: 5430.0 },
    { price: 4.3400, amount: 3800, total: 16492.0 },
    { price: 4.3370, amount: 2100, total: 9107.7 },
    { price: 4.3340, amount: 5500, total: 23837.0 },
    { price: 4.3320, amount: 890,  total: 3855.5 },
    { price: 4.3310, amount: 4200, total: 18190.2 },
    { price: 4.3300, amount: 11000, total: 47630.0 },
  ],
  bids: [
    { price: 4.3295, amount: 8900, total: 38532.6 },
    { price: 4.3280, amount: 3200, total: 13849.6 },
    { price: 4.3260, amount: 6700, total: 28984.2 },
    { price: 4.3240, amount: 1400, total: 6053.6 },
    { price: 4.3210, amount: 9200, total: 39753.2 },
    { price: 4.3180, amount: 2800, total: 12090.4 },
    { price: 4.3150, amount: 5100, total: 22006.5 },
  ],
};

export const RECENT_TRADES = [
  { price: 4.720, amount: 350, time: '14:32:18', type: 'buy' },
  { price: 4.718, amount: 1200, time: '14:32:15', type: 'sell' },
  { price: 4.720, amount: 800, time: '14:32:11', type: 'buy' },
  { price: 4.722, amount: 550, time: '14:32:08', type: 'buy' },
  { price: 4.719, amount: 2100, time: '14:32:02', type: 'sell' },
  { price: 4.715, amount: 3400, time: '14:31:58', type: 'sell' },
  { price: 4.720, amount: 900, time: '14:31:45', type: 'buy' },
];

export const P2P_LISTINGS = [
  {
    id: '1',
    trader: 'KofiAsante_GH',
    coin: 'BTNG',
    type: 'sell',
    price: 4.85,
    minAmount: 100,
    maxAmount: 5000,
    available: 12000,
    currency: 'GHS',
    paymentMethods: ['MTN MoMo', 'Bank Transfer'],
    completedTrades: 245,
    rating: 4.9,
    badge: 'Verified',
    responseTime: '< 5 min',
    country: 'Ghana',
  },
  {
    id: '2',
    trader: 'AmaOsei_GH',
    coin: 'BTNG',
    type: 'buy',
    price: 4.68,
    minAmount: 50,
    maxAmount: 8000,
    available: 20000,
    currency: 'GHS',
    paymentMethods: ['Airtel Money', 'Bank Transfer'],
    completedTrades: 189,
    rating: 4.8,
    badge: 'Premium',
    responseTime: '< 3 min',
    country: 'Ghana',
  },
  {
    id: '3',
    trader: 'KwameNkrumah9',
    coin: 'BTC',
    type: 'sell',
    price: 107_800,
    minAmount: 10,
    maxAmount: 50000,
    available: 2.5,
    currency: 'USD',
    paymentMethods: ['Bank Wire', 'SWIFT'],
    completedTrades: 412,
    rating: 5.0,
    badge: 'Elite',
    responseTime: '< 10 min',
    country: 'Nigeria',
  },
  {
    id: '4',
    trader: 'AbenaFosua',
    coin: 'USDT',
    type: 'sell',
    price: 1.02,
    minAmount: 20,
    maxAmount: 10000,
    available: 50000,
    currency: 'GHS',
    paymentMethods: ['MTN MoMo', 'Vodafone Cash'],
    completedTrades: 78,
    rating: 4.7,
    badge: 'Verified',
    responseTime: '< 15 min',
    country: 'Ghana',
  },
];

export const COPY_TRADERS = [
  {
    id: '1',
    name: 'KwakuBrobbey',
    avatar: 'KB',
    country: 'Ghana',
    roi30d: 47.3,
    roi7d: 12.8,
    winRate: 78,
    followers: 3240,
    aum: 8_400_000,
    pnl30d: 412_000,
    risk: 'Medium',
    specialty: ['BTNG', 'BTC', 'ETH'],
    badge: 'Elite Trader',
    verified: true,
    strategy: 'BTNG spot + swing trading with African market timing',
  },
  {
    id: '2',
    name: 'AdwoaFinance',
    avatar: 'AF',
    country: 'Ghana',
    roi30d: 31.5,
    roi7d: 8.4,
    winRate: 85,
    followers: 1890,
    aum: 3_200_000,
    pnl30d: 187_000,
    risk: 'Low',
    specialty: ['BTNG', 'USDT'],
    badge: 'Safe Trader',
    verified: true,
    strategy: 'Conservative BTNG accumulation strategy',
  },
  {
    id: '3',
    name: 'NanaYaw_Crypto',
    avatar: 'NY',
    country: 'Ghana',
    roi30d: 89.2,
    roi7d: 22.1,
    winRate: 65,
    followers: 5670,
    aum: 15_800_000,
    pnl30d: 980_000,
    risk: 'High',
    specialty: ['BTNG', 'SOL', 'BNB'],
    badge: 'Top Performer',
    verified: true,
    strategy: 'Aggressive multi-coin momentum strategy',
  },
  {
    id: '4',
    name: 'EsiBimpong',
    avatar: 'EB',
    country: 'Ghana',
    roi30d: 22.8,
    roi7d: 5.9,
    winRate: 81,
    followers: 920,
    aum: 1_100_000,
    pnl30d: 68_000,
    risk: 'Low',
    specialty: ['BTC', 'ETH', 'BTNG'],
    badge: 'Steady',
    verified: false,
    strategy: 'DCA + hold strategy for long-term wealth',
  },
];

export const TRANSACTIONS = [
  { id: '1', type: 'buy', coin: 'BTNG', amount: 1000, price: 4.31, value: 4310, date: '2026-05-20', status: 'completed' },
  { id: '2', type: 'deposit', coin: 'USDT', amount: 5000, price: 1.0, value: 5000, date: '2026-05-18', status: 'completed' },
  { id: '3', type: 'sell', coin: 'BTC', amount: 0.01, price: 105_200, value: 1052, date: '2026-05-17', status: 'completed' },
  { id: '4', type: 'receive', coin: 'BTNG', amount: 500, price: 4.20, value: 2100, date: '2026-05-15', status: 'completed' },
  { id: '5', type: 'withdraw', coin: 'USDT', amount: 200, price: 1.0, value: 200, date: '2026-05-12', status: 'pending' },
  { id: '6', type: 'buy', coin: 'ETH', amount: 0.5, price: 3720, value: 1860, date: '2026-05-10', status: 'completed' },
];

export const PAYMENT_METHODS = [
  { id: '1', name: 'MTN MoMo', type: 'mobile_money', country: 'Ghana', icon: '📱', color: '#FFCC00' },
  { id: '2', name: 'Vodafone Cash', type: 'mobile_money', country: 'Ghana', icon: '📱', color: '#E60000' },
  { id: '3', name: 'AirtelTigo Money', type: 'mobile_money', country: 'Ghana', icon: '📱', color: '#FF6600' },
  { id: '4', name: 'GCB Bank', type: 'bank', country: 'Ghana', icon: '🏦', color: '#003366' },
  { id: '5', name: 'Bank Transfer', type: 'bank', country: 'International', icon: '🏦', color: '#1E3A5F' },
  { id: '6', name: 'SWIFT Wire', type: 'international', country: 'International', icon: '🌐', color: '#0066CC' },
];

export const MOCK_USER = {
  id: 'user_btng_001',
  name: 'John Mensah',
  email: 'john.mensah@btng.gold',
  phone: '+233 24 123 4567',
  country: 'Ghana',
  kycStatus: 'verified',
  twoFAEnabled: true,
  referralCode: 'BTNG-JOHN-2024',
  referralCount: 12,
  referralEarned: 240,
  joinDate: '2024-01-15',
  totalPortfolioValue: 28_970,
  totalPnL: 4_840,
  totalPnLPct: 20.1,
  practiceBalance: 100_000,
  tier: 'Gold',
};

export const REFERRAL_DATA = {
  code: 'BTNG-JOHN-2024',
  link: 'https://btng.gold/join?ref=BTNG-JOHN-2024',
  tier: 'Gold',
  commissionRate: 0.02,
  totalEarned: 624.80,
  pendingEarnings: 38.40,
  paidOut: 586.40,
  totalReferrals: 12,
  activeReferrals: 9,
  thisMonthEarnings: 218.20,
  lastMonthEarnings: 184.60,
};

export const REFERRAL_TIERS = [
  { tier: 'Bronze', minReferrals: 0, commission: 1.0, color: '#CD7F32', icon: '🥉' },
  { tier: 'Silver', minReferrals: 5, commission: 1.5, color: '#C0C0C0', icon: '🥈' },
  { tier: 'Gold', minReferrals: 10, commission: 2.0, color: '#D4A017', icon: '🥇' },
  { tier: 'Platinum', minReferrals: 25, commission: 2.5, color: '#E5E4E2', icon: '💎' },
  { tier: 'Diamond', minReferrals: 50, commission: 3.0, color: '#B9F2FF', icon: '💠' },
];

export const REFERRED_USERS = [
  {
    id: 'r1',
    name: 'Kwabena Asante',
    initials: 'KA',
    email: 'k.asante@email.com',
    country: 'Ghana',
    joinDate: '2026-04-12',
    status: 'active',
    totalVolume: 28_400,
    tradeCount: 47,
    earned: 142.00,
    lastActive: '2026-05-24',
    kycVerified: true,
  },
  {
    id: 'r2',
    name: 'Ama Darko',
    initials: 'AD',
    email: 'ama.darko@email.com',
    country: 'Ghana',
    joinDate: '2026-04-20',
    status: 'active',
    totalVolume: 15_200,
    tradeCount: 31,
    earned: 96.80,
    lastActive: '2026-05-23',
    kycVerified: true,
  },
  {
    id: 'r3',
    name: 'Yaw Mensah',
    initials: 'YM',
    email: 'y.mensah@email.com',
    country: 'Ghana',
    joinDate: '2026-05-01',
    status: 'active',
    totalVolume: 9_800,
    tradeCount: 18,
    earned: 58.40,
    lastActive: '2026-05-22',
    kycVerified: true,
  },
  {
    id: 'r4',
    name: 'Abena Osei',
    initials: 'AO',
    email: 'abena.o@email.com',
    country: 'Nigeria',
    joinDate: '2026-05-05',
    status: 'active',
    totalVolume: 6_200,
    tradeCount: 12,
    earned: 38.40,
    lastActive: '2026-05-25',
    kycVerified: false,
  },
  {
    id: 'r5',
    name: 'Kofi Boateng',
    initials: 'KB',
    email: 'kofi.b@email.com',
    country: 'Ghana',
    joinDate: '2026-05-10',
    status: 'pending',
    totalVolume: 1_200,
    tradeCount: 3,
    earned: 12.00,
    lastActive: '2026-05-18',
    kycVerified: false,
  },
  {
    id: 'r6',
    name: 'Efua Amponsah',
    initials: 'EA',
    email: 'efua.a@email.com',
    country: 'Ghana',
    joinDate: '2026-05-14',
    status: 'inactive',
    totalVolume: 0,
    tradeCount: 0,
    earned: 0,
    lastActive: '2026-05-14',
    kycVerified: false,
  },
  {
    id: 'r7',
    name: 'Nana Adjei',
    initials: 'NA',
    email: 'nana.adj@email.com',
    country: 'Ivory Coast',
    joinDate: '2026-05-16',
    status: 'active',
    totalVolume: 4_800,
    tradeCount: 9,
    earned: 28.80,
    lastActive: '2026-05-24',
    kycVerified: true,
  },
  {
    id: 'r8',
    name: 'Akua Sarpong',
    initials: 'AS',
    email: 'akua.s@email.com',
    country: 'Ghana',
    joinDate: '2026-05-18',
    status: 'pending',
    totalVolume: 800,
    tradeCount: 2,
    earned: 6.40,
    lastActive: '2026-05-20',
    kycVerified: false,
  },
];

export const REFERRAL_COMMISSION_HISTORY = [
  { id: 'c1', user: 'Kwabena Asante', trade: 'BTNG/USDT', volume: 4200, commission: 84.00, date: '2026-05-24 14:32', status: 'paid' },
  { id: 'c2', user: 'Ama Darko', trade: 'BTC/USDT', volume: 1850, commission: 37.00, date: '2026-05-24 11:18', status: 'paid' },
  { id: 'c3', user: 'Yaw Mensah', trade: 'BTNG/USDT', volume: 920, commission: 18.40, date: '2026-05-23 16:45', status: 'paid' },
  { id: 'c4', user: 'Nana Adjei', trade: 'ETH/USDT', volume: 1200, commission: 24.00, date: '2026-05-23 09:12', status: 'paid' },
  { id: 'c5', user: 'Abena Osei', trade: 'BTNG/USDT', volume: 960, commission: 19.20, date: '2026-05-22 20:33', status: 'pending' },
  { id: 'c6', user: 'Kofi Boateng', trade: 'USDT/GHS', volume: 600, commission: 12.00, date: '2026-05-21 13:55', status: 'pending' },
  { id: 'c7', user: 'Kwabena Asante', trade: 'BTNG/USDT', volume: 2900, commission: 58.00, date: '2026-05-20 18:20', status: 'paid' },
  { id: 'c8', user: 'Ama Darko', trade: 'SOL/USDT', volume: 750, commission: 15.00, date: '2026-05-19 10:08', status: 'paid' },
];

export const ADMIN_STATS = {
  totalUsers: 14_820,
  activeUsers: 8_340,
  totalVolume24h: 312_450_000,
  totalRevenue30d: 2_840_000,
  pendingKYC: 142,
  pendingWithdrawals: 38,
  totalDeposits: 89_200_000,
  totalWithdrawals: 61_400_000,
};

export interface BlogArticle {
  id: string;
  category: string;
  title: string;
  summary: string;
  content: string;
  author: string;
  authorAvatar: string;
  date: string;
  readTime: string;
  image: string;
  imageColor: string;
  tags: string[];
  views: number;
  bookmarked: boolean;
  featured: boolean;
}

export const BLOG_ARTICLES: BlogArticle[] = [
  {
    id: 'b1',
    category: 'BTNG',
    title: 'BTNG Gold Coin Surges 47% in May — What Is Driving the Rally?',
    summary: 'BTNG Gold Coin has posted remarkable gains this month as institutional interest from West African sovereign funds intensifies and the MTN MoMo integration goes live.',
    content: 'BTNG Gold Coin (BTNG) has emerged as one of the top-performing digital assets in May 2026, posting a 47.3% gain that has outpaced even Bitcoin and Ethereum over the same period.\n\nWHAT IS DRIVING THE RALLY\n\nThe surge is being attributed to several converging factors:\n\n1. MTN MoMo Integration\nThe seamless integration of MTN Mobile Money — Africa\'s largest mobile payments network — has unlocked a new wave of retail investors across Ghana, Nigeria, Uganda, and Cameroon. Users can now deposit and withdraw BTNG directly via MoMo with zero foreign exchange friction.\n\n2. Sovereign Fund Interest\nMultiple West African sovereign wealth funds have reportedly taken exploratory positions in BTNG as a "digital gold" reserve alternative. Ghana\'s Mineral Income Investment Fund (MIIF) is said to be reviewing a 1% allocation to BTNG.\n\n3. African Gold Peg Narrative\nBTNG\'s positioning as a digitally-native representation of African gold reserves has resonated strongly with retail and institutional investors alike as traditional gold prices continue to rise globally.\n\nPRICE OUTLOOK\n\nTechnical analysts tracking BTNG point to the $5.50 level as the next key resistance zone. A breakout above that level would set BTNG on a trajectory toward $7.00 — a level that would represent a 300% gain from January 2026 lows.\n\nSupport levels to watch: $4.40 / $4.20 / $3.95\n\n"BTNG is not just another meme coin. It has real utility, real infrastructure, and a real user base across 54 African nations." — KwakuBrobbey, Elite Trader, BTNG Exchange\n\nCONCLUSION\n\nWhile crypto markets remain volatile, BTNG\'s unique positioning at the intersection of African mobile money, gold reserves, and DeFi infrastructure gives it a differentiated thesis that few other assets can match in 2026.',
    author: 'BTNG Research',
    authorAvatar: '📊',
    date: '2026-05-24',
    readTime: '5 min read',
    image: '💰',
    imageColor: '#D4A017',
    tags: ['BTNG', 'Price Analysis', 'Ghana'],
    views: 12_840,
    bookmarked: false,
    featured: true,
  },
  {
    id: 'b2',
    category: 'Ghana',
    title: 'Bank of Ghana Issues Framework for Crypto Asset Regulation',
    summary: 'The Bank of Ghana has released its long-awaited Virtual Asset Service Provider (VASP) framework, providing regulatory clarity for crypto exchanges including BTNG Gold.',
    content: 'The Bank of Ghana (BoG) released its Virtual Asset Service Provider (VASP) regulatory framework on May 20th, 2026 — a landmark development that positions Ghana as one of Africa\'s most crypto-progressive jurisdictions.\n\nKEY PROVISIONS\n\nLicensing Requirements:\n- All crypto exchanges serving Ghanaian residents must obtain a VASP license within 12 months\n- Minimum capital requirement: GHS 2,000,000 (~$130,000 USD)\n- Mandatory AML/KYC compliance aligned with FATF standards\n\nConsumer Protection:\n- Cold storage requirement: At least 80% of customer funds must be held in offline cold wallets\n- Mandatory insurance for exchange hot wallets\n- Monthly proof-of-reserves publication requirement\n\nBTNG Gold Response:\nBTNG Gold has announced full compliance readiness, having anticipated this regulatory framework for over 18 months. The platform\'s existing KYC infrastructure, cold storage solution, and reserve auditing practices exceed the minimum requirements.\n\nIMPACT ON THE GHANAIAN CRYPTO MARKET\n\nAnalysts expect this framework to unlock significant institutional capital that has been sitting on the sidelines awaiting regulatory clarity. Several Ghanaian pension funds are reportedly ready to allocate up to 2% of their portfolios to regulated crypto assets.\n\n"Ghana is setting the standard for responsible crypto regulation in Africa. This framework protects consumers while fostering innovation." — Dr. Kwame Asante, BoG Deputy Governor\n\nWHAT THIS MEANS FOR BTNG USERS\n\nBTNG Gold users in Ghana can expect full regulatory compliance by Q3 2026, including enhanced consumer protections and the ability to use BTNG as collateral for bank loans under the new framework.',
    author: 'Ghana Crypto Desk',
    authorAvatar: '🇬🇭',
    date: '2026-05-22',
    readTime: '4 min read',
    image: '🏛️',
    imageColor: '#2E7D32',
    tags: ['Ghana', 'Regulation', 'BoG'],
    views: 8_920,
    bookmarked: true,
    featured: true,
  },
  {
    id: 'b3',
    category: 'Market',
    title: 'Bitcoin Crosses $107K: African Exchanges See Record Trading Volume',
    summary: 'Bitcoin has broken through the $107,000 resistance level, triggering record trading volumes across African crypto platforms including BTNG Gold.',
    content: 'Bitcoin (BTC) crossed the $107,000 milestone on May 23rd, 2026, triggering a wave of trading activity across the African continent. BTNG Gold Exchange reported a 340% spike in BTC/USDT trading volume within 24 hours of the breakout.\n\nTHE AFRICAN BITCOIN STORY\n\nAfrica has quietly become one of the fastest-growing Bitcoin adoption regions globally. Driven by currency devaluation in Nigeria, remittance needs across the diaspora, and increasing mobile penetration, African retail investors are increasingly treating Bitcoin as a savings vehicle.\n\nKey Statistics (May 2026):\n- Africa accounts for 14.2% of global P2P Bitcoin trading volume\n- Ghana P2P volume up 280% year-over-year\n- Nigeria remains the continent\'s largest Bitcoin market by volume\n\nMARKET TECHNICALS\n\nBTC\'s breakout above $107K was accompanied by:\n- Record institutional inflows of $2.8B in a single week\n- Bitcoin options market signaling $120K target for Q3 2026\n- On-chain data showing long-term holder accumulation at multi-year highs\n\nALTCOIN IMPLICATIONS\n\nBitcoin\'s rally has had a positive spillover effect on the broader crypto market, with BTNG Gold outperforming the market with an 8.34% gain on the same day. Analysts expect altcoin season to accelerate if BTC stabilizes above $105K.',
    author: 'Market Analysis Team',
    authorAvatar: '₿',
    date: '2026-05-23',
    readTime: '3 min read',
    image: '📈',
    imageColor: '#F7931A',
    tags: ['Bitcoin', 'Market', 'Africa'],
    views: 24_500,
    bookmarked: false,
    featured: false,
  },
  {
    id: 'b4',
    category: 'DeFi',
    title: 'BTNG DeFi Ecosystem Launches: Staking, Yield, and Liquidity Pools',
    summary: 'The BTNG DeFi suite goes live with staking rewards up to 18% APY, BTNG/USDT liquidity pools, and a governance token for platform decision-making.',
    content: 'The BTNG DeFi Ecosystem officially launched on May 15th, 2026, bringing a full suite of decentralized finance products to the BTNG Gold platform.\n\nWHAT LAUNCHED\n\nBTNG Staking — Up to 18% APY:\nUsers can now stake BTNG tokens for flexible or fixed-term periods:\n- Flexible: 8% APY, unstake anytime\n- 30-Day Lock: 12% APY\n- 90-Day Lock: 18% APY\n- Minimum stake: 100 BTNG\n\nLiquidity Pools:\nThe BTNG/USDT liquidity pool went live with $12M in initial liquidity. Liquidity providers earn 0.3% of every trade proportional to their pool share.\n\nBTNG Governance Token (BGTV):\nA new governance token has been introduced, giving BTNG stakers voting rights on fee structure changes, new coin listings, and the DeFi product roadmap.\n\nWHY THIS MATTERS FOR AFRICAN USERS\n\nDeFi has historically been complex and inaccessible for non-technical users. BTNG\'s DeFi suite is designed mobile-first with simplified flows, MoMo on-ramps, and customer support in local languages.\n\n"We want every Ghanaian grandmother to be able to earn 18% APY on her BTNG savings. DeFi should not be for Silicon Valley only." — BTNG Product Team\n\nRISK DISCLAIMER\n\nDeFi products carry smart contract and market risks. Users are advised to only stake funds they can afford to hold through market volatility periods.',
    author: 'DeFi Desk',
    authorAvatar: '⚡',
    date: '2026-05-20',
    readTime: '6 min read',
    image: '🔗',
    imageColor: '#9945FF',
    tags: ['DeFi', 'Staking', 'BTNG'],
    views: 6_340,
    bookmarked: false,
    featured: false,
  },
  {
    id: 'b5',
    category: 'BTNG',
    title: 'BTNG Wallet 2.0: NFC Payments, Offline Mode and Multi-Chain Support',
    summary: 'The next major BTNG Wallet update introduces tap-to-pay NFC for in-store purchases, offline transaction signing, and support for Ethereum, Solana, and BNB Chain.',
    content: 'BTNG Wallet 2.0 is scheduled to launch in June 2026, bringing a set of features that will fundamentally transform how Africans interact with digital assets in their daily lives.\n\nFEATURE HIGHLIGHTS\n\nNFC Tap-to-Pay:\nUsing your phone\'s Near Field Communication chip, you will soon be able to pay for goods and services at any BTNG-enabled merchant by simply tapping your phone. The integration works with Android 9+ and iOS 14+ devices.\n\nOffline Transaction Signing:\nIn areas with poor internet connectivity — a real challenge across rural Africa — BTNG Wallet 2.0 will allow users to pre-sign transactions offline. Once connectivity is restored, the signed transaction is broadcast automatically.\n\nMulti-Chain Support:\nBTNG Wallet will now hold assets across:\n- BTNG Native Chain\n- Ethereum (ETH, ERC-20 tokens)\n- Solana (SOL, SPL tokens)\n- BNB Chain (BNB, BEP-20 tokens)\n\nHardware Wallet Integration:\nLedger and Trezor hardware wallet support will be added for users holding large balances who require the highest security tier.\n\nTIMELINE\n\n- Beta testing: June 2026\n- Public launch: July 2026\n- NFC merchant network: Q4 2026',
    author: 'BTNG Product',
    authorAvatar: '🏦',
    date: '2026-05-19',
    readTime: '4 min read',
    image: '📱',
    imageColor: '#D4A017',
    tags: ['BTNG', 'Wallet', 'NFC'],
    views: 9_120,
    bookmarked: false,
    featured: false,
  },
  {
    id: 'b6',
    category: 'Ghana',
    title: 'MTN Ghana and BTNG Gold Ink Strategic Partnership for MoMo Integration',
    summary: 'MTN Ghana and BTNG Gold Exchange have signed a strategic partnership enabling 20 million MoMo users to buy, sell, and hold BTNG directly from their MoMo wallets.',
    content: 'MTN Ghana and BTNG Gold Exchange have announced a landmark strategic partnership that will allow MTN\'s 20 million Mobile Money subscribers to access BTNG crypto services directly within the MoMo app.\n\nPARTNERSHIP DETAILS\n\nUnder the agreement:\n- MTN MoMo users can purchase BTNG with zero conversion fees for the first 6 months\n- BTNG holders can cash out directly to their MoMo wallet in GHS\n- MTN will pre-load BTNG Wallet as a featured app for all MoMo users in Ghana\n\nWHY THIS IS TRANSFORMATIONAL\n\nThis partnership bridges the gap between Ghana\'s massive mobile money user base and the crypto economy. With 20 million potential new BTNG users gaining seamless access, this represents the single largest crypto adoption catalyst in West African history.\n\nKey Numbers:\n- MTN Ghana MoMo active users: 20.4 million\n- Average MoMo transaction value: GHS 280 (~$18 USD)\n- BTNG minimum purchase: GHS 5 (~$0.32 USD) — designed for micro-investment\n\nROLL-OUT TIMELINE\n\n- Phase 1 (June 2026): BTNG purchase/sell via MoMo for KYC-verified users\n- Phase 2 (August 2026): BTNG transfer to other MoMo numbers\n- Phase 3 (Q4 2026): In-store BTNG payments at MoMo merchants',
    author: 'BTNG Press',
    authorAvatar: '📡',
    date: '2026-05-17',
    readTime: '3 min read',
    image: '🤝',
    imageColor: '#FFCC00',
    tags: ['Ghana', 'MTN', 'Partnership'],
    views: 18_760,
    bookmarked: true,
    featured: false,
  },
  {
    id: 'b7',
    category: 'Market',
    title: 'Africa Crypto Market Cap Hits $850B: The Continental Digital Gold Rush',
    summary: 'The combined market capitalization of crypto assets held by African investors has surpassed $850 billion for the first time, cementing Africa as a top-3 global crypto region.',
    content: 'Africa\'s aggregate crypto market capitalization has crossed the $850 billion mark for the first time in history, according to a new report from the African Digital Asset Framework (ADAF).\n\nTHE NUMBERS\n\n- Total African crypto holdings: $847B (up from $320B in 2025)\n- Year-over-year growth: +165%\n- Top markets: Nigeria ($280B), South Africa ($195B), Ghana ($87B), Kenya ($61B)\n- BTNG Gold\'s share of African crypto: $4.72B (0.56%)\n\nDRIVERS OF GROWTH\n\n1. Currency Devaluation Hedge\nMultiple African currencies have faced significant devaluation pressure in 2025-2026. Citizens are increasingly turning to crypto — especially BTNG and Bitcoin — as stores of value.\n\n2. Remittance Revolution\nCrypto remittances now account for 31% of all inbound remittances to sub-Saharan Africa, up from 8% in 2023. BTNG\'s low transaction fees make it particularly suited for diaspora transfers.\n\n3. Generational Wealth Transfer\nAfrica\'s young, mobile-first population (60% under 25) has embraced crypto as a default investment vehicle, bypassing traditional banking infrastructure entirely.\n\nOUTLOOK\n\nIf current growth rates continue, analysts project African crypto holdings could reach $2 trillion by end of 2027 — placing Africa at par with Europe as a global crypto hub.',
    author: 'Macro Research',
    authorAvatar: '🌍',
    date: '2026-05-15',
    readTime: '5 min read',
    image: '🌍',
    imageColor: '#2E7D32',
    tags: ['Market', 'Africa', 'Growth'],
    views: 31_200,
    bookmarked: false,
    featured: false,
  },
  {
    id: 'b8',
    category: 'DeFi',
    title: 'Understanding BTNG Yield Farming: A Beginner Guide for African Investors',
    summary: 'Yield farming can feel complex, but with BTNG the process is streamlined for mobile-first African investors. Here is everything you need to know to get started earning passive income.',
    content: 'Yield farming — the practice of earning rewards by providing liquidity to DeFi protocols — is now accessible to every BTNG user through our simplified mobile interface.\n\nWHAT IS YIELD FARMING\n\nWhen you farm yield, you deposit your crypto assets into a liquidity pool. In return, you earn a portion of the trading fees generated by that pool, plus bonus token rewards.\n\nThink of it like depositing money in a savings account — except the returns can be 10-20x higher than traditional bank rates.\n\nBTNG YIELD FARMING OPTIONS\n\nOption 1: BTNG Single Staking\n- Deposit: BTNG only\n- Current APY: 8-18% (varies by lock period)\n- Risk Level: Low\n- Best for: Long-term BTNG holders\n\nOption 2: BTNG/USDT Liquidity Pool\n- Deposit: Equal value of BTNG + USDT\n- Current APY: 24% (variable)\n- Risk Level: Medium (impermanent loss risk)\n- Best for: Active traders comfortable with DeFi mechanics\n\nOption 3: BTNG/BTC Liquidity Pool\n- Deposit: Equal value of BTNG + BTC\n- Current APY: 31% (variable)\n- Risk Level: Higher\n- Best for: Experienced DeFi users\n\nGETTING STARTED IN 3 STEPS\n\n1. Go to Wallet and select the DeFi tab\n2. Choose your pool and review APY and risk level\n3. Deposit and confirm — earnings start immediately\n\nIMPORTANT RISKS\n\n- Smart contract bugs (BTNG conducts quarterly audits)\n- Impermanent loss in LP positions\n- APY rates fluctuate with trading volume\n\nAlways start with small amounts while learning.',
    author: 'BTNG Education',
    authorAvatar: '🎓',
    date: '2026-05-12',
    readTime: '7 min read',
    image: '🌾',
    imageColor: '#22C55E',
    tags: ['DeFi', 'Education', 'Yield'],
    views: 14_800,
    bookmarked: false,
    featured: false,
  },
];
